### ISSUE TITLE
POE dependency seems to fail on Windows

### ISSUE THREAD

**Issue by mrcaron** [moritz/ilbot#44]
Not sure if it fails on versions other than Win 8 Enterprise (which is what I'm installing on). But it's dead in the water on POE dependency install. Wish I could try this, looks good!

**Comment by zoffixznet** [comment]
Would you provide more information? What Perl are you using (Strawberry, ActiveState, etc) and which version?

Also, would you provide the output of the failure?

**Comment by moritz** [comment]
@mrcaron please submit POE failures to install here: https://rt.cpan.org/Public/Dist/Display.html?Name=POE

ilbot isn't tested under windows, and I won't support it there, but I'll accept patches to improve things in WIndows
