### ISSUE TITLE
Long Links Get Broken in Web Log Display

### ISSUE THREAD

**Issue by zoffixznet** [moritz/ilbot#51]
Long links get broken in web display (when copy-pasted as part of the other text), e.g. this one: https://irclog.perlgeek.de/moarvm/2017-04-14#i_14427338

Worse, they LOOK fine, it's only when someone tries to visit them, possibly in an emailed email or link posted elsewhere do they realize there's an issue.

The problem is due to ZWS `&#8203;` being stuffed into the link, I assume, by log generator.

That should be removed and CSS's `word-wrap: break-word` property used instead to break long chunks of contiguous text.

**Comment by moritz** [comment]
Just for the record: the URL in the link is fine, it's the link text that includes the zero-width space.

**Comment by moritz** [comment]
Thanks for the report @zoffixznet, I think d1b1fc0cca4ffb3f919cc75da38b846757f0fe4c has fixed it.

**Comment by zoffixznet** [comment]
Looking closer at it, seems [it doesn't wrap anything any more](https://irclog.perlgeek.de/perl6/2017-04-24#i_14476928)

It's because all the stuff's in a table, which is set to auto-expand, so it does just that.

One fix I see for that is adding `table-layout: fixed` to the table and adding three `<col>`s so you could size the columns, BUT, that wouldn't auto-resize the nick column (just whatever width you'd pick for it). It's possible to figure out the length with JS and use that, but that feel's kinda messy.

```html
    <table id="log" style="clear:both; table-layout: fixed">
      <col style="width: 4.5em"><col><col>
        <tr class="head">
              ...
```
