### ISSUE TITLE
STDIN is not a socket: specify a listen location

### ISSUE THREAD

**Issue by Miniontoby** [moritz/ilbot#54]
When I run: `perl /var/www/htdocs/ilbot/bin/ilbot2.pl config/bot.conf` it works fine

But when i try to go to the website I get 500 error.

Then i try using the console: `perl /var/www/htdocs/ilbot/www/ilbot.fcgi`: 

`Setting timezone to UTC! at /var/www/htdocs/ilbot/lib/Ilbot/Backend/SQL.pm line 43.
STDIN is not a socket: specify a listen location at /usr/local/libdata/perl5/site_perl/Plack/Handler/FCGI.pm line 57.`

How to fix this?

Greets Miniontoby

**Comment by zoffixznet** [comment]
Don't know anything about this codebase, but are you sure you're not supposed to run it using the `plackup` command that comes with [`Plack`](https://metacpan.org/pod/Plack)?

**Comment by Miniontoby** [comment]
> Don't know anything about this codebase, but are you sure you're not supposed to run it using the `plackup` command that comes with [`Plack`](https://metacpan.org/pod/Plack)?

I runned: `plackup /var/www/htdocs/ilbot/www/ilbot.psgi` 

it says: `Setting timezone to UTC! at /var/www/htdocs/ilbot/lib/Ilbot/Backend/SQL.pm line 43.
HTTP::Server::PSGI: Accepting connections at http://0:5000/
`
And it doesn't exit yet. but yeah idk if that's the way it is intented, but I will try and reply with more info when i tried it

**Comment by zoffixznet** [comment]
Yeah, it starts the server at http://localhost:5000/ and listens for connections.

**Comment by Miniontoby** [comment]
> Yeah, it starts the server at http://localhost:5000/ and listens for connections.

I have redirected it to my subdomain, but I am missing the static files and such

the thing i tried was just using the 'logic' of the apache part and implement it into my httpd server, but it runs into a 500 error and yeah i also copied the file and added a listener, but didn't solve anything. It says `No such file or directory (500 Internal Server Error)` in logs

**Comment by Miniontoby** [comment]
I fixed it: 
My /var/www/htdocs/ilbot/www/ilbot.fcgi has this content now that fixed it:

```
#!/usr/bin/env plackup -s FCGI
use lib '/var/www/htdocs/ilbot/lib'; use Ilbot::Config '/var/www/htdocs/ilbot/config';
use 5.010;
use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";
use Plack::Util qw/load_psgi/;

my $app = Plack::Util::load_psgi("$FindBin::Bin/ilbot.psgi");

use Plack::Handler::FCGI;
my $server = Plack::Handler::FCGI->new(
    nproc  => '3',
    listen => [ '/var/www/run/fcgi.sock' ],
    detach => 0,
);
$server->run($app);
```

Then use `plackup -s FCGI --listen /var/www/run/fcgi.sock /var/www/htdocs/ilbot/www/ilbot.fcgi` to run the socket and then just connect to the website using the apache thing (I dont have it but yeah its just the default one)
